### ISSUE TITLE
Bluetooth not found my esp32 

### ISSUE THREAD

**Issue by wh1ter0z** [simondankelmann/SubMarine#14]
Hi 
I compiled and tested on my Samsung S10 (4g) (rooted) 

Apps runs well but my esp32 not found (all permission granted) 

In bluetooth i found it manualy but in android app never show ....

UPDATE: on XIAOMI X5 5G works (CHANGE BLUETOOTH SETTING PERMISSION GRANT) but on my S10 not shown an popup or something else 

And i think its not optimised for phone like mine 

my phone : S10 4G SM-G973F/DS 
Ram 8GB 
System: Rooted / BOOTLOADER OPEN

![Screenshot_20231206-222153_Sub Marine](https://github.com/simondankelmann/SubMarine/assets/69695347/a8851a39-30a2-485a-9307-709a63aa2ea7)

Also > 3 dots option on top it has settings button 

Settings button not work ... (tested on both phones)

**Comment by simondankelmann** [comment]
acutally settings button does not do anything at the moment :P
what android version is the phone that doesnt work please ?

**Comment by wh1ter0z** [comment]
> acutally settings button does not do anything at the moment :P
> what android version is the phone that doesnt work please ?

ANDROID 11 (API 30) 
samsung s10 4g SM-G973F/DS

**Comment by wh1ter0z** [comment]
> can you try this:
> 
> https://github.com/simondankelmann/SubMarine/blob/main/Android/SubMarine/app/debug/app-debug.apk
> 
> i changed something in the bleutooth permission request.

I will try now

**Comment by wh1ter0z** [comment]
> can you try this:
> 
> https://github.com/simondankelmann/SubMarine/blob/main/Android/SubMarine/app/debug/app-debug.apk
> 
> i changed something in the bleutooth permission request.

Same , not show Submarine Bluetooth in app

**Comment by simondankelmann** [comment]
hmm strange...

**Comment by wh1ter0z** [comment]
> hmm strange...

Any idea to fix it?

**Comment by simondankelmann** [comment]
can you maybe try to hook up your phone to the pc and run the app from android studio, maybe something is in the adb log

**Comment by wh1ter0z** [comment]
> can you maybe try to hook up your phone to the pc and run the app from android studio, maybe something is in the adb log

Android studio is filtered but at night i can do it 

Now 15:05 (Iran)

**Comment by wh1ter0z** [comment]
> let me know :)

I will 

If u have telegram please give me your id or u can text me @Thereisnomind

**Comment by wh1ter0z** [comment]
![20231208_193653.jpg](https://github.com/simondankelmann/SubMarine/assets/69695347/4c992053-ea21-4ce7-925a-c8826902a5db)

Scan not granted

**Comment by simondankelmann** [comment]
i changed it 20 minutes ago after your post :)

**Comment by wh1ter0z** [comment]
> https://github.com/simondankelmann/SubMarine/commit/f749e52d9273574f6687d974fccdc55203581b01

Fixed sir ❤👍 

Thanks for help

**Comment by simondankelmann** [comment]
nice :) thank you for the logs. maybe this helps some more people with sdk level 30 and below !
