### ISSUE TITLE
Apk bluetooth error

### ISSUE THREAD

**Issue by xcypher78** [simondankelmann/SubMarine#2]
Hi, when i click on Bluetooth button for search devices app give me error and i need close the app

**Comment by simondankelmann** [comment]
Hello, can you tell me what that error says ? You could try to manually grant all requested permissions to the app on your device. Maybe bluetooth or location access is permitted and therefore the app crashes

**Comment by xcypher78** [comment]
All good now :) i manually granted all acess permissions thanks
